/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTaskReviewsRouteImport } from './routes/admin.task-reviews'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as EmployeeCompletedRouteImport } from './routes/employee.completed'
import { Route as EmployeeHistoryRouteImport } from './routes/employee.history'
import { Route as EmployeeLeaderboardRouteImport } from './routes/employee.leaderboard'
import { Route as EmployeeNoticesRouteImport } from './routes/employee.notices'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee.notifications'
import { Route as EmployeePendingRouteImport } from './routes/employee.pending'
import { Route as EmployeePendingReviewRouteImport } from './routes/employee.pending-review'
import { Route as EmployeePerformanceRouteImport } from './routes/employee.performance'
import { Route as EmployeePointsRouteImport } from './routes/employee.points'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeRejectedRouteImport } from './routes/employee.rejected'
import { Route as EmployeeSettingsRouteImport } from './routes/employee.settings'
import { Route as EmployeeStatisticsRouteImport } from './routes/employee.statistics'
import { Route as EmployeeTasksRouteImport } from './routes/employee.tasks'
import { Route as AdminAdminsIndexRouteImport } from './routes/admin.admins.index'
import { Route as AdminAdminsIdRouteImport } from './routes/admin.admins.$id'
import { Route as AdminAdminsNewRouteImport } from './routes/admin.admins.new'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin.employees.index'
import { Route as AdminEmployeesIdRouteImport } from './routes/admin.employees.$id'
import { Route as AdminEmployeesNewRouteImport } from './routes/admin.employees.new'
import { Route as AdminTasksIndexRouteImport } from './routes/admin.tasks.index'
import { Route as AdminTasksIdRouteImport } from './routes/admin.tasks.$id'
import { Route as AdminTasksNewRouteImport } from './routes/admin.tasks.new'
import { Route as EmployeeTasksIndexRouteImport } from './routes/employee.tasks.index'
import { Route as EmployeeTasksIdRouteImport } from './routes/employee.tasks.$id'
import { Route as AdminAdminsIdEditRouteImport } from './routes/admin.admins.$id.edit'
import { Route as AdminEmployeesIdEditRouteImport } from './routes/admin.employees.$id.edit'
import { Route as AdminTasksIdEditRouteImport } from './routes/admin.tasks.$id.edit'
import { Route as EmployeeTasksIdIndexRouteImport } from './routes/employee.tasks.$id.index'
import { Route as EmployeeTasksIdSubmissionRouteImport } from './routes/employee.tasks.$id.submission'
import { Route as EmployeeTasksIdSubmitRouteImport } from './routes/employee.tasks.$id.submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaskReviewsRoute = AdminTaskReviewsRouteImport.update({
  id: '/task-reviews',
  path: '/task-reviews',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeCompletedRoute = EmployeeCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeHistoryRoute = EmployeeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLeaderboardRoute = EmployeeLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNoticesRoute = EmployeeNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePendingRoute = EmployeePendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePendingReviewRoute = EmployeePendingReviewRouteImport.update({
  id: '/pending-review',
  path: '/pending-review',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePerformanceRoute = EmployeePerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePointsRoute = EmployeePointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeRejectedRoute = EmployeeRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeSettingsRoute = EmployeeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeStatisticsRoute = EmployeeStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeTasksRoute = EmployeeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminAdminsIndexRoute = AdminAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsIdRoute = AdminAdminsIdRouteImport.update({
  id: '/admins/$id',
  path: '/admins/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsNewRoute = AdminAdminsNewRouteImport.update({
  id: '/admins/new',
  path: '/admins/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesIdRoute = AdminEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesNewRoute = AdminEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksIdRoute = AdminTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeTasksIndexRoute = EmployeeTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeTasksRoute,
} as any)
const EmployeeTasksIdRoute = EmployeeTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeeTasksRoute,
} as any)
const AdminAdminsIdEditRoute = AdminAdminsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminAdminsIdRoute,
} as any)
const AdminEmployeesIdEditRoute = AdminEmployeesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminEmployeesIdRoute,
} as any)
const AdminTasksIdEditRoute = AdminTasksIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminTasksIdRoute,
} as any)
const EmployeeTasksIdIndexRoute = EmployeeTasksIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeTasksIdRoute,
} as any)
const EmployeeTasksIdSubmissionRoute =
  EmployeeTasksIdSubmissionRouteImport.update({
    id: '/submission',
    path: '/submission',
    getParentRoute: () => EmployeeTasksIdRoute,
  } as any)
const EmployeeTasksIdSubmitRoute = EmployeeTasksIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => EmployeeTasksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/task-reviews': typeof AdminTaskReviewsRoute
  '/employee/completed': typeof EmployeeCompletedRoute
  '/employee/history': typeof EmployeeHistoryRoute
  '/employee/leaderboard': typeof EmployeeLeaderboardRoute
  '/employee/notices': typeof EmployeeNoticesRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/pending': typeof EmployeePendingRoute
  '/employee/pending-review': typeof EmployeePendingReviewRoute
  '/employee/performance': typeof EmployeePerformanceRoute
  '/employee/points': typeof EmployeePointsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/rejected': typeof EmployeeRejectedRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/employee/statistics': typeof EmployeeStatisticsRoute
  '/employee/tasks': typeof EmployeeTasksRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/admin/admins/$id': typeof AdminAdminsIdRouteWithChildren
  '/admin/admins/new': typeof AdminAdminsNewRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRouteWithChildren
  '/admin/employees/new': typeof AdminEmployeesNewRoute
  '/admin/tasks/$id': typeof AdminTasksIdRouteWithChildren
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/employee/tasks/$id': typeof EmployeeTasksIdRouteWithChildren
  '/admin/admins/': typeof AdminAdminsIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/employee/tasks/': typeof EmployeeTasksIndexRoute
  '/admin/admins/$id/edit': typeof AdminAdminsIdEditRoute
  '/admin/employees/$id/edit': typeof AdminEmployeesIdEditRoute
  '/admin/tasks/$id/edit': typeof AdminTasksIdEditRoute
  '/employee/tasks/$id/submission': typeof EmployeeTasksIdSubmissionRoute
  '/employee/tasks/$id/submit': typeof EmployeeTasksIdSubmitRoute
  '/employee/tasks/$id/': typeof EmployeeTasksIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/task-reviews': typeof AdminTaskReviewsRoute
  '/employee/completed': typeof EmployeeCompletedRoute
  '/employee/history': typeof EmployeeHistoryRoute
  '/employee/leaderboard': typeof EmployeeLeaderboardRoute
  '/employee/notices': typeof EmployeeNoticesRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/pending': typeof EmployeePendingRoute
  '/employee/pending-review': typeof EmployeePendingReviewRoute
  '/employee/performance': typeof EmployeePerformanceRoute
  '/employee/points': typeof EmployeePointsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/rejected': typeof EmployeeRejectedRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/employee/statistics': typeof EmployeeStatisticsRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/admin/admins/$id': typeof AdminAdminsIdRouteWithChildren
  '/admin/admins/new': typeof AdminAdminsNewRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRouteWithChildren
  '/admin/employees/new': typeof AdminEmployeesNewRoute
  '/admin/tasks/$id': typeof AdminTasksIdRouteWithChildren
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/admins': typeof AdminAdminsIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/employee/tasks': typeof EmployeeTasksIndexRoute
  '/admin/admins/$id/edit': typeof AdminAdminsIdEditRoute
  '/admin/employees/$id/edit': typeof AdminEmployeesIdEditRoute
  '/admin/tasks/$id/edit': typeof AdminTasksIdEditRoute
  '/employee/tasks/$id/submission': typeof EmployeeTasksIdSubmissionRoute
  '/employee/tasks/$id/submit': typeof EmployeeTasksIdSubmitRoute
  '/employee/tasks/$id': typeof EmployeeTasksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/task-reviews': typeof AdminTaskReviewsRoute
  '/employee/completed': typeof EmployeeCompletedRoute
  '/employee/history': typeof EmployeeHistoryRoute
  '/employee/leaderboard': typeof EmployeeLeaderboardRoute
  '/employee/notices': typeof EmployeeNoticesRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/pending': typeof EmployeePendingRoute
  '/employee/pending-review': typeof EmployeePendingReviewRoute
  '/employee/performance': typeof EmployeePerformanceRoute
  '/employee/points': typeof EmployeePointsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/rejected': typeof EmployeeRejectedRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/employee/statistics': typeof EmployeeStatisticsRoute
  '/employee/tasks': typeof EmployeeTasksRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/admin/admins/$id': typeof AdminAdminsIdRouteWithChildren
  '/admin/admins/new': typeof AdminAdminsNewRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRouteWithChildren
  '/admin/employees/new': typeof AdminEmployeesNewRoute
  '/admin/tasks/$id': typeof AdminTasksIdRouteWithChildren
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/employee/tasks/$id': typeof EmployeeTasksIdRouteWithChildren
  '/admin/admins/': typeof AdminAdminsIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/employee/tasks/': typeof EmployeeTasksIndexRoute
  '/admin/admins/$id/edit': typeof AdminAdminsIdEditRoute
  '/admin/employees/$id/edit': typeof AdminEmployeesIdEditRoute
  '/admin/tasks/$id/edit': typeof AdminTasksIdEditRoute
  '/employee/tasks/$id/submission': typeof EmployeeTasksIdSubmissionRoute
  '/employee/tasks/$id/submit': typeof EmployeeTasksIdSubmitRoute
  '/employee/tasks/$id/': typeof EmployeeTasksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/employee'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/activity'
    | '/admin/audit-logs'
    | '/admin/leaderboard'
    | '/admin/notices'
    | '/admin/notifications'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/task-reviews'
    | '/employee/completed'
    | '/employee/history'
    | '/employee/leaderboard'
    | '/employee/notices'
    | '/employee/notifications'
    | '/employee/pending'
    | '/employee/pending-review'
    | '/employee/performance'
    | '/employee/points'
    | '/employee/profile'
    | '/employee/rejected'
    | '/employee/settings'
    | '/employee/statistics'
    | '/employee/tasks'
    | '/admin/'
    | '/employee/'
    | '/admin/admins/$id'
    | '/admin/admins/new'
    | '/admin/employees/$id'
    | '/admin/employees/new'
    | '/admin/tasks/$id'
    | '/admin/tasks/new'
    | '/employee/tasks/$id'
    | '/admin/admins/'
    | '/admin/employees/'
    | '/admin/tasks/'
    | '/employee/tasks/'
    | '/admin/admins/$id/edit'
    | '/admin/employees/$id/edit'
    | '/admin/tasks/$id/edit'
    | '/employee/tasks/$id/submission'
    | '/employee/tasks/$id/submit'
    | '/employee/tasks/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/activity'
    | '/admin/audit-logs'
    | '/admin/leaderboard'
    | '/admin/notices'
    | '/admin/notifications'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/task-reviews'
    | '/employee/completed'
    | '/employee/history'
    | '/employee/leaderboard'
    | '/employee/notices'
    | '/employee/notifications'
    | '/employee/pending'
    | '/employee/pending-review'
    | '/employee/performance'
    | '/employee/points'
    | '/employee/profile'
    | '/employee/rejected'
    | '/employee/settings'
    | '/employee/statistics'
    | '/admin'
    | '/employee'
    | '/admin/admins/$id'
    | '/admin/admins/new'
    | '/admin/employees/$id'
    | '/admin/employees/new'
    | '/admin/tasks/$id'
    | '/admin/tasks/new'
    | '/admin/admins'
    | '/admin/employees'
    | '/admin/tasks'
    | '/employee/tasks'
    | '/admin/admins/$id/edit'
    | '/admin/employees/$id/edit'
    | '/admin/tasks/$id/edit'
    | '/employee/tasks/$id/submission'
    | '/employee/tasks/$id/submit'
    | '/employee/tasks/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/employee'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/activity'
    | '/admin/audit-logs'
    | '/admin/leaderboard'
    | '/admin/notices'
    | '/admin/notifications'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/task-reviews'
    | '/employee/completed'
    | '/employee/history'
    | '/employee/leaderboard'
    | '/employee/notices'
    | '/employee/notifications'
    | '/employee/pending'
    | '/employee/pending-review'
    | '/employee/performance'
    | '/employee/points'
    | '/employee/profile'
    | '/employee/rejected'
    | '/employee/settings'
    | '/employee/statistics'
    | '/employee/tasks'
    | '/admin/'
    | '/employee/'
    | '/admin/admins/$id'
    | '/admin/admins/new'
    | '/admin/employees/$id'
    | '/admin/employees/new'
    | '/admin/tasks/$id'
    | '/admin/tasks/new'
    | '/employee/tasks/$id'
    | '/admin/admins/'
    | '/admin/employees/'
    | '/admin/tasks/'
    | '/employee/tasks/'
    | '/admin/admins/$id/edit'
    | '/admin/employees/$id/edit'
    | '/admin/tasks/$id/edit'
    | '/employee/tasks/$id/submission'
    | '/employee/tasks/$id/submit'
    | '/employee/tasks/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/task-reviews': {
      id: '/admin/task-reviews'
      path: '/task-reviews'
      fullPath: '/admin/task-reviews'
      preLoaderRoute: typeof AdminTaskReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/completed': {
      id: '/employee/completed'
      path: '/completed'
      fullPath: '/employee/completed'
      preLoaderRoute: typeof EmployeeCompletedRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/history': {
      id: '/employee/history'
      path: '/history'
      fullPath: '/employee/history'
      preLoaderRoute: typeof EmployeeHistoryRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/leaderboard': {
      id: '/employee/leaderboard'
      path: '/leaderboard'
      fullPath: '/employee/leaderboard'
      preLoaderRoute: typeof EmployeeLeaderboardRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/notices': {
      id: '/employee/notices'
      path: '/notices'
      fullPath: '/employee/notices'
      preLoaderRoute: typeof EmployeeNoticesRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/pending': {
      id: '/employee/pending'
      path: '/pending'
      fullPath: '/employee/pending'
      preLoaderRoute: typeof EmployeePendingRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/pending-review': {
      id: '/employee/pending-review'
      path: '/pending-review'
      fullPath: '/employee/pending-review'
      preLoaderRoute: typeof EmployeePendingReviewRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/performance': {
      id: '/employee/performance'
      path: '/performance'
      fullPath: '/employee/performance'
      preLoaderRoute: typeof EmployeePerformanceRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/points': {
      id: '/employee/points'
      path: '/points'
      fullPath: '/employee/points'
      preLoaderRoute: typeof EmployeePointsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/rejected': {
      id: '/employee/rejected'
      path: '/rejected'
      fullPath: '/employee/rejected'
      preLoaderRoute: typeof EmployeeRejectedRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/settings': {
      id: '/employee/settings'
      path: '/settings'
      fullPath: '/employee/settings'
      preLoaderRoute: typeof EmployeeSettingsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/statistics': {
      id: '/employee/statistics'
      path: '/statistics'
      fullPath: '/employee/statistics'
      preLoaderRoute: typeof EmployeeStatisticsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/tasks': {
      id: '/employee/tasks'
      path: '/tasks'
      fullPath: '/employee/tasks'
      preLoaderRoute: typeof EmployeeTasksRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/admins/': {
      id: '/admin/admins/'
      path: '/admins'
      fullPath: '/admin/admins/'
      preLoaderRoute: typeof AdminAdminsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins/$id': {
      id: '/admin/admins/$id'
      path: '/admins/$id'
      fullPath: '/admin/admins/$id'
      preLoaderRoute: typeof AdminAdminsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins/new': {
      id: '/admin/admins/new'
      path: '/admins/new'
      fullPath: '/admin/admins/new'
      preLoaderRoute: typeof AdminAdminsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees/$id': {
      id: '/admin/employees/$id'
      path: '/employees/$id'
      fullPath: '/admin/employees/$id'
      preLoaderRoute: typeof AdminEmployeesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees/new': {
      id: '/admin/employees/new'
      path: '/employees/new'
      fullPath: '/admin/employees/new'
      preLoaderRoute: typeof AdminEmployeesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks/$id': {
      id: '/admin/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/admin/tasks/$id'
      preLoaderRoute: typeof AdminTasksIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks/new': {
      id: '/admin/tasks/new'
      path: '/tasks/new'
      fullPath: '/admin/tasks/new'
      preLoaderRoute: typeof AdminTasksNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employee/tasks/': {
      id: '/employee/tasks/'
      path: '/'
      fullPath: '/employee/tasks/'
      preLoaderRoute: typeof EmployeeTasksIndexRouteImport
      parentRoute: typeof EmployeeTasksRoute
    }
    '/employee/tasks/$id': {
      id: '/employee/tasks/$id'
      path: '/$id'
      fullPath: '/employee/tasks/$id'
      preLoaderRoute: typeof EmployeeTasksIdRouteImport
      parentRoute: typeof EmployeeTasksRoute
    }
    '/admin/admins/$id/edit': {
      id: '/admin/admins/$id/edit'
      path: '/edit'
      fullPath: '/admin/admins/$id/edit'
      preLoaderRoute: typeof AdminAdminsIdEditRouteImport
      parentRoute: typeof AdminAdminsIdRoute
    }
    '/admin/employees/$id/edit': {
      id: '/admin/employees/$id/edit'
      path: '/edit'
      fullPath: '/admin/employees/$id/edit'
      preLoaderRoute: typeof AdminEmployeesIdEditRouteImport
      parentRoute: typeof AdminEmployeesIdRoute
    }
    '/admin/tasks/$id/edit': {
      id: '/admin/tasks/$id/edit'
      path: '/edit'
      fullPath: '/admin/tasks/$id/edit'
      preLoaderRoute: typeof AdminTasksIdEditRouteImport
      parentRoute: typeof AdminTasksIdRoute
    }
    '/employee/tasks/$id/': {
      id: '/employee/tasks/$id/'
      path: '/'
      fullPath: '/employee/tasks/$id/'
      preLoaderRoute: typeof EmployeeTasksIdIndexRouteImport
      parentRoute: typeof EmployeeTasksIdRoute
    }
    '/employee/tasks/$id/submission': {
      id: '/employee/tasks/$id/submission'
      path: '/submission'
      fullPath: '/employee/tasks/$id/submission'
      preLoaderRoute: typeof EmployeeTasksIdSubmissionRouteImport
      parentRoute: typeof EmployeeTasksIdRoute
    }
    '/employee/tasks/$id/submit': {
      id: '/employee/tasks/$id/submit'
      path: '/submit'
      fullPath: '/employee/tasks/$id/submit'
      preLoaderRoute: typeof EmployeeTasksIdSubmitRouteImport
      parentRoute: typeof EmployeeTasksIdRoute
    }
  }
}

interface AdminAdminsIdRouteChildren {
  AdminAdminsIdEditRoute: typeof AdminAdminsIdEditRoute
}

const AdminAdminsIdRouteChildren: AdminAdminsIdRouteChildren = {
  AdminAdminsIdEditRoute: AdminAdminsIdEditRoute,
}

const AdminAdminsIdRouteWithChildren = AdminAdminsIdRoute._addFileChildren(
  AdminAdminsIdRouteChildren,
)

interface AdminEmployeesIdRouteChildren {
  AdminEmployeesIdEditRoute: typeof AdminEmployeesIdEditRoute
}

const AdminEmployeesIdRouteChildren: AdminEmployeesIdRouteChildren = {
  AdminEmployeesIdEditRoute: AdminEmployeesIdEditRoute,
}

const AdminEmployeesIdRouteWithChildren =
  AdminEmployeesIdRoute._addFileChildren(AdminEmployeesIdRouteChildren)

interface AdminTasksIdRouteChildren {
  AdminTasksIdEditRoute: typeof AdminTasksIdEditRoute
}

const AdminTasksIdRouteChildren: AdminTasksIdRouteChildren = {
  AdminTasksIdEditRoute: AdminTasksIdEditRoute,
}

const AdminTasksIdRouteWithChildren = AdminTasksIdRoute._addFileChildren(
  AdminTasksIdRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTaskReviewsRoute: typeof AdminTaskReviewsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdminsIdRoute: typeof AdminAdminsIdRouteWithChildren
  AdminAdminsNewRoute: typeof AdminAdminsNewRoute
  AdminEmployeesIdRoute: typeof AdminEmployeesIdRouteWithChildren
  AdminEmployeesNewRoute: typeof AdminEmployeesNewRoute
  AdminTasksIdRoute: typeof AdminTasksIdRouteWithChildren
  AdminTasksNewRoute: typeof AdminTasksNewRoute
  AdminAdminsIndexRoute: typeof AdminAdminsIndexRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTaskReviewsRoute: AdminTaskReviewsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdminsIdRoute: AdminAdminsIdRouteWithChildren,
  AdminAdminsNewRoute: AdminAdminsNewRoute,
  AdminEmployeesIdRoute: AdminEmployeesIdRouteWithChildren,
  AdminEmployeesNewRoute: AdminEmployeesNewRoute,
  AdminTasksIdRoute: AdminTasksIdRouteWithChildren,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminAdminsIndexRoute: AdminAdminsIndexRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeTasksIdRouteChildren {
  EmployeeTasksIdSubmissionRoute: typeof EmployeeTasksIdSubmissionRoute
  EmployeeTasksIdSubmitRoute: typeof EmployeeTasksIdSubmitRoute
  EmployeeTasksIdIndexRoute: typeof EmployeeTasksIdIndexRoute
}

const EmployeeTasksIdRouteChildren: EmployeeTasksIdRouteChildren = {
  EmployeeTasksIdSubmissionRoute: EmployeeTasksIdSubmissionRoute,
  EmployeeTasksIdSubmitRoute: EmployeeTasksIdSubmitRoute,
  EmployeeTasksIdIndexRoute: EmployeeTasksIdIndexRoute,
}

const EmployeeTasksIdRouteWithChildren = EmployeeTasksIdRoute._addFileChildren(
  EmployeeTasksIdRouteChildren,
)

interface EmployeeTasksRouteChildren {
  EmployeeTasksIdRoute: typeof EmployeeTasksIdRouteWithChildren
  EmployeeTasksIndexRoute: typeof EmployeeTasksIndexRoute
}

const EmployeeTasksRouteChildren: EmployeeTasksRouteChildren = {
  EmployeeTasksIdRoute: EmployeeTasksIdRouteWithChildren,
  EmployeeTasksIndexRoute: EmployeeTasksIndexRoute,
}

const EmployeeTasksRouteWithChildren = EmployeeTasksRoute._addFileChildren(
  EmployeeTasksRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeCompletedRoute: typeof EmployeeCompletedRoute
  EmployeeHistoryRoute: typeof EmployeeHistoryRoute
  EmployeeLeaderboardRoute: typeof EmployeeLeaderboardRoute
  EmployeeNoticesRoute: typeof EmployeeNoticesRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeePendingRoute: typeof EmployeePendingRoute
  EmployeePendingReviewRoute: typeof EmployeePendingReviewRoute
  EmployeePerformanceRoute: typeof EmployeePerformanceRoute
  EmployeePointsRoute: typeof EmployeePointsRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeRejectedRoute: typeof EmployeeRejectedRoute
  EmployeeSettingsRoute: typeof EmployeeSettingsRoute
  EmployeeStatisticsRoute: typeof EmployeeStatisticsRoute
  EmployeeTasksRoute: typeof EmployeeTasksRouteWithChildren
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeCompletedRoute: EmployeeCompletedRoute,
  EmployeeHistoryRoute: EmployeeHistoryRoute,
  EmployeeLeaderboardRoute: EmployeeLeaderboardRoute,
  EmployeeNoticesRoute: EmployeeNoticesRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeePendingRoute: EmployeePendingRoute,
  EmployeePendingReviewRoute: EmployeePendingReviewRoute,
  EmployeePerformanceRoute: EmployeePerformanceRoute,
  EmployeePointsRoute: EmployeePointsRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeRejectedRoute: EmployeeRejectedRoute,
  EmployeeSettingsRoute: EmployeeSettingsRoute,
  EmployeeStatisticsRoute: EmployeeStatisticsRoute,
  EmployeeTasksRoute: EmployeeTasksRouteWithChildren,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
